const B=require("./base.js");
const {Document,Packer,Paragraph,AlignmentType,BorderStyle,ShadingType,LevelFormat,TextRun,
 PW,PH,ML,MR,MT,MB,CW,FONT,SZ,SZ_H1,C,T,sp,PB,body,note,keypt,H1,H2,H3,tocEntry,
 codeBlock,bull,twoColTable,threeColTable,makeHeader,makeFooter,img}=B;
const fs=require("fs"), path=require("path");
const IMG=n=>path.join(__dirname,"img",n+".png");
const TITLE="BÁO CÁO KHÁM PHÁ DỮ LIỆU";
const DS="Student Depression Dataset";
const H4=(n,t)=>new Paragraph({children:[T(`${n}  ${t}`,{size:28,bold:true,color:C.navy})],
  spacing:{before:160,after:80},indent:{left:360},outlineLevel:2});

const doc=new Document({
 numbering:{config:[
  {reference:"b1",levels:[{level:0,format:LevelFormat.BULLET,text:"•",alignment:AlignmentType.LEFT,
   style:{paragraph:{indent:{left:720,hanging:360}}}}]},
  {reference:"n1",levels:[{level:0,format:LevelFormat.DECIMAL,text:"%1.",alignment:AlignmentType.LEFT,
   style:{paragraph:{indent:{left:700,hanging:340}}}}]}]},
 styles:{default:{document:{run:{font:FONT,size:SZ}}},
  paragraphStyles:[
   {id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,
    run:{size:SZ_H1,bold:true,font:FONT,color:C.white},paragraph:{spacing:{before:240,after:200},outlineLevel:0}},
   {id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,
    run:{size:28,bold:true,font:FONT,color:C.accent},paragraph:{spacing:{before:200,after:120},outlineLevel:1}}]},
 sections:[{
  properties:{page:{size:{width:PW,height:PH},margin:{top:MT,right:MR,bottom:MB,left:ML}}},
  headers:{default:makeHeader(`${TITLE} — ${DS}`)},
  footers:{default:makeFooter("Báo cáo khám phá dữ liệu (EDA) — Student Depression Dataset")},
  children:[

/* ══ BÌA ══ */
sp(560),
new Paragraph({children:[T("MÔN TRÍ TUỆ NHÂN TẠO ỨNG DỤNG",{size:24,bold:true,color:C.gray})],
 alignment:AlignmentType.CENTER,spacing:{after:60}}),
new Paragraph({children:[T(TITLE,{size:40,bold:true,color:C.navy})],
 alignment:AlignmentType.CENTER,spacing:{after:20}}),
new Paragraph({children:[T("Exploratory Data Analysis — EDA",{size:24,italics:true,color:C.gray})],
 alignment:AlignmentType.CENTER,spacing:{after:70}}),
new Paragraph({children:[T("STUDENT DEPRESSION DATASET",{size:40,bold:true,color:C.accent})],
 alignment:AlignmentType.CENTER,shading:{fill:C.exBg,type:ShadingType.CLEAR},spacing:{before:80,after:80}}),
new Paragraph({children:[T("27.901 sinh viên  ·  18 biến  ·  502.218 ô dữ liệu",{size:26,color:C.gray,italics:true})],
 alignment:AlignmentType.CENTER,spacing:{after:260}}),
twoColTable([
 ["Tệp phân tích","student_depression_GOC.csv (bản chưa xử lý)"],
 ["Nguồn","Kaggle — Student Depression Dataset"],
 ["Mục đích","Trả lời yêu cầu 1 của đề bài: phân tích khám phá dữ liệu"],
 ["Công cụ","Python 3 · pandas · scipy · matplotlib; trợ lý AI hỗ trợ đặt câu hỏi khám phá"],
 ["Nguyên tắc","Mọi con số trong báo cáo đều do mã Python tạo ra và đã được chạy lại để đối chiếu"],
 ["Người thực hiện","……………………………………"],
 ["Ngày lập báo cáo","……………………………………"],
],3000,CW-3000),
sp(220),
body("Tóm tắt điều hành: Bộ dữ liệu có 27.901 bản ghi và 18 biến, gần như không có giá trị khuyết (3 ô, chiếm 0,011%) và không có bản ghi trùng lặp. Tuy nhiên, khảo sát chi tiết phát hiện bốn vấn đề chất lượng cần xử lý trước khi phân tích: ba cột gần như hằng số, 28 giá trị nằm ngoài thang đo, 65 nhãn rác dạng “Others”, và 26 ô trong cột Thành phố chứa dữ liệu lạc chỗ. Về mối quan hệ, ba yếu tố liên quan mạnh nhất tới trầm cảm là ý định tự tử, áp lực học tập và áp lực tài chính; ngược lại điểm trung bình học tập và giới tính gần như không liên quan. Các biến độc lập hầu như không tương quan với nhau, nên không có vấn đề đa cộng tuyến."),
PB(),

/* ══ MỤC LỤC ══ */
new Paragraph({children:[new TextRun({text:"MỤC LỤC",font:FONT,size:36,bold:true,color:C.black})],
 alignment:AlignmentType.CENTER,
 border:{bottom:{style:BorderStyle.SINGLE,size:6,color:C.border,space:8}},spacing:{before:0,after:340}}),
tocEntry("1. MỤC TIÊU VÀ PHƯƠNG PHÁP",3,0),
tocEntry("2. TỔNG QUAN BỘ DỮ LIỆU",4,0),
tocEntry("2.1  Quy mô và cấu trúc",4,1),
tocEntry("2.2  Danh mục 18 biến",4,1),
tocEntry("3. ĐÁNH GIÁ CHẤT LƯỢNG DỮ LIỆU",6,0),
tocEntry("3.1  Giá trị khuyết và bản ghi trùng",6,1),
tocEntry("3.2  Bốn vấn đề phát hiện được",6,1),
tocEntry("4. PHÂN TÍCH ĐƠN BIẾN",8,0),
tocEntry("4.1  Biến số: thống kê mô tả",8,1),
tocEntry("4.2  Phân bố bốn biến số chính",8,1),
tocEntry("4.3  Phát hiện ngoại lai",9,1),
tocEntry("4.4  Biến phân loại",10,1),
tocEntry("4.5  Biến mục tiêu",11,1),
tocEntry("5. PHÂN TÍCH HAI BIẾN",12,0),
tocEntry("5.1  Biến số so với biến mục tiêu",12,1),
tocEntry("5.1.1  Biểu đồ phân tán: vì sao CGPA không phân biệt được",13,2),
tocEntry("5.2  Biến phân loại so với biến mục tiêu",14,1),
tocEntry("5.2.1  Biểu đồ phân tán cấp thành phố",15,2),
tocEntry("5.3  Tương quan giữa các biến độc lập",17,1),
tocEntry("5.3.1  Bảng xếp hạng tổng hợp",18,2),
tocEntry("6. NHẬN ĐỊNH VÀ ĐỀ XUẤT BƯỚC TIẾP THEO",19,0),
tocEntry("7. HẠN CHẾ CỦA BƯỚC KHÁM PHÁ",21,0),
PB(),

/* ══ 1 ══ */
new Paragraph({children:[T("1. MỤC TIÊU VÀ PHƯƠNG PHÁP",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
body("Phân tích khám phá dữ liệu là bước đầu tiên của mọi dự án phân tích. Mục đích không phải kiểm định giả thuyết, mà là hiểu bộ dữ liệu có gì, chất lượng ra sao, và những hướng phân tích nào đáng theo đuổi."),
H2("Mục tiêu","Báo cáo này trả lời năm câu hỏi"),
bull("Bộ dữ liệu có quy mô và cấu trúc thế nào? Mỗi biến mang ý nghĩa gì?"),
bull("Chất lượng dữ liệu ra sao? Có cần tiền xử lý không, và cần xử lý những gì?"),
bull("Từng biến phân bố thế nào? Có giá trị ngoại lai hay bất thường không?"),
bull("Biến nào có liên hệ với biến mục tiêu? Mạnh hay yếu?"),
bull("Các biến độc lập có tương quan với nhau không (vấn đề đa cộng tuyến)?"),
H2("Phương pháp","Quy trình bốn bước"),
threeColTable([
 ["Bước 1","Tổng quan","Đọc tệp, kiểm tra kích thước, kiểu dữ liệu, bộ nhớ chiếm dụng."],
 ["Bước 2","Chất lượng","Đếm giá trị khuyết, bản ghi trùng, cột gần như hằng số, giá trị ngoài thang đo, nhãn rác."],
 ["Bước 3","Đơn biến","Thống kê mô tả, độ lệch, độ nhọn, ngoại lai theo quy tắc 1,5×IQR cho biến số; tần suất và số mức cho biến phân loại."],
 ["Bước 4","Hai biến","Tương quan point-biserial và kiểm định t cho biến số; kiểm định chi-square và hệ số Cramér's V cho biến phân loại."],
],[1100,1800,CW-2900],["Bước","Nội dung","Kỹ thuật sử dụng"]),
keypt("Vai trò của AI trong báo cáo này: trợ lý AI được dùng để gợi ý danh mục câu hỏi khám phá và sinh mã Python. Toàn bộ con số đều do nhóm chạy lại bằng Python và đối chiếu, không lấy trực tiếp từ câu trả lời của AI."),
PB(),

/* ══ 2 ══ */
new Paragraph({children:[T("2. TỔNG QUAN BỘ DỮ LIỆU",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
H2("2.1","Quy mô và cấu trúc"),
twoColTable([
 ["Số bản ghi","27.901 sinh viên"],
 ["Số biến","18 cột"],
 ["Tổng số ô","502.218"],
 ["Bộ nhớ chiếm dụng","13,89 MB"],
 ["Biến kiểu số","10 cột"],
 ["Biến kiểu chữ","8 cột"],
 ["Biến mục tiêu","Depression — nhị phân 0/1"],
],3000,CW-3000),
body("Quy mô này đủ lớn để các kiểm định thống kê có hiệu lực cao, nhưng cũng đủ nhỏ để xử lý trên máy tính cá nhân thông thường. Lưu ý: với cỡ mẫu gần 28.000, hầu hết khác biệt đều đạt ý nghĩa thống kê, vì vậy khi diễn giải phải xem thêm độ lớn hiệu ứng chứ không chỉ nhìn p-value."),
H2("2.2","Danh mục 18 biến"),
threeColTable([
 ["id","Số","Mã định danh bản ghi — không mang thông tin phân tích"],
 ["Gender","Chữ","Giới tính: Male / Female"],
 ["Age","Số","Tuổi, từ 18 đến 59"],
 ["City","Chữ","Thành phố — 52 giá trị khác nhau"],
 ["Profession","Chữ","Nghề nghiệp — 14 giá trị, 99,89% là “Student”"],
 ["Academic Pressure","Số","Áp lực học tập, thang 1–5"],
 ["Work Pressure","Số","Áp lực công việc, thang 0–5 — 99,99% bằng 0"],
 ["CGPA","Số","Điểm trung bình tích lũy, thang 0–10"],
 ["Study Satisfaction","Số","Mức hài lòng việc học, thang 1–5"],
 ["Job Satisfaction","Số","Mức hài lòng công việc — 99,97% bằng 0"],
 ["Sleep Duration","Chữ","Thời lượng ngủ — 5 nhóm"],
 ["Dietary Habits","Chữ","Chế độ ăn — 4 nhóm"],
 ["Degree","Chữ","Bằng cấp đang theo học — 28 giá trị"],
 ["Have you ever had suicidal thoughts ?","Chữ","Từng có ý định tự tử: Yes / No"],
 ["Work/Study Hours","Số","Số giờ học hoặc làm mỗi ngày, 0–12"],
 ["Financial Stress","Số","Áp lực tài chính, thang 1–5 — có 3 ô khuyết"],
 ["Family History of Mental Illness","Chữ","Gia đình có người mắc bệnh tâm thần: Yes / No"],
 ["Depression","Số","BIẾN MỤC TIÊU — nhị phân 0/1"],
],[3000,900,CW-3900],["Tên biến","Kiểu","Ý nghĩa và ghi chú"]),
PB(),

/* ══ 3 ══ */
new Paragraph({children:[T("3. ĐÁNH GIÁ CHẤT LƯỢNG DỮ LIỆU",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
H2("3.1","Giá trị khuyết và bản ghi trùng"),
twoColTable([
 ["Tổng số ô khuyết","3 ô trên 502.218 — chiếm 0,0006%"],
 ["Vị trí","Toàn bộ nằm ở cột Financial Stress (0,011% của cột này)"],
 ["Bản ghi trùng hoàn toàn","0 — sau khi đã loại cột id khỏi phép so sánh"],
],3800,CW-3800),
note("Khi kiểm tra trùng lặp, bắt buộc phải loại cột định danh (ở đây là id) trước khi so sánh. Nếu giữ lại, mỗi dòng đều có mã riêng nên kết quả luôn bằng 0 và ta sẽ bỏ sót trùng lặp thật."),
keypt("Ở hai chỉ số cơ bản nhất, bộ dữ liệu này rất sạch. Nhưng “không khuyết, không trùng” chưa đủ để kết luận là sạch — mục 3.2 cho thấy điều đó."),
H2("3.2","Bốn vấn đề phát hiện được"),
H4("Vấn đề 1","Ba cột gần như hằng số"),
threeColTable([
 ["Profession","99,89% là “Student”","Chỉ 31 bản ghi không phải sinh viên"],
 ["Work Pressure","99,99% bằng 0","Chỉ 3 bản ghi khác 0"],
 ["Job Satisfaction","99,97% bằng 0","Chỉ 8 bản ghi khác 0"],
],[2400,2200,CW-4600],["Cột","Mức độ tập trung","Chi tiết"]),
body("Nguyên nhân rõ ràng: gần như toàn bộ người trả lời là sinh viên, nên hai biến liên quan tới công việc không áp dụng được. Ba cột này không phân biệt được gì giữa các bản ghi, giữ lại chỉ làm nhiễu mô hình."),
H4("Vấn đề 2","Giá trị nằm ngoài thang đo"),
threeColTable([
 ["Academic Pressure","Thang 1–5","9 ô có giá trị 0"],
 ["Study Satisfaction","Thang 1–5","10 ô có giá trị 0"],
 ["CGPA","Thang 0,01–10","9 sinh viên có CGPA đúng bằng 0"],
],[2400,1800,CW-4200],["Cột","Thang đo hợp lệ","Vi phạm"]),
body("Tổng cộng 28 ô. Chín sinh viên có CGPA bằng 0 thuộc các bằng cấp Class 12 (7 người), BBA (1) và M.Ed (1) — không có lý do hợp lý để một sinh viên đang theo học có điểm tích lũy đúng bằng 0, nên đây là giá trị thiếu được mã hóa nhầm thành 0."),
H4("Vấn đề 3","Nhãn rác dạng “Others”"),
twoColTable([
 ["Sleep Duration","18 ô"],["Dietary Habits","12 ô"],["Degree","35 ô"],["Tổng","65 ô"],
],3400,CW-3400),
H4("Vấn đề 4","Dữ liệu lạc chỗ trong cột Thành phố"),
body("Cột City có 52 giá trị, trong đó chỉ 30 giá trị xuất hiện từ 10 bản ghi trở lên. 22 nhãn còn lại (tổng 26 dòng) không phải tên thành phố:"),
...codeBlock([
 "Saanvi, Bhavna, Harsha, Gaurav, Harsh, Reyansh, Rashi,",
 "Mira, Vaanya, Mihir, Nalini, Nandini, Kibara, Nalyan,",
 "M.Tech, M.Com, ME, City, 3.0, Khaziabad,",
 "Less Delhi, Less than 5 Kalyan",
]),
threeColTable([
 ["Tên người","12 nhãn","Saanvi, Bhavna, Gaurav, Reyansh… — tên riêng lọt vào cột thành phố"],
 ["Mã bằng cấp","3 nhãn","M.Tech, M.Com, ME — thuộc cột Degree"],
 ["Chuỗi lỗi ghép","2 nhãn","“Less Delhi”, “Less than 5 Kalyan” — giá trị cột Sleep Duration dính vào tên thành phố"],
 ["Khác","5 nhãn","“City” (tên cột lọt vào dữ liệu), “3.0” (số), và tên viết sai"],
],[2000,1400,CW-3400],["Nhóm","Số nhãn","Mô tả"]),
keypt("Hai chuỗi “Less Delhi” và “Less than 5 Kalyan” là bằng chứng quan trọng nhất: chúng cho thấy quy trình nhập liệu bị LỆCH CỘT, không phải lỗi gõ nhầm ngẫu nhiên. Điều này buộc ta phải kiểm tra kỹ các cột còn lại."),
twoColTable([["Tổng số ô cần can thiệp","122 ô — chiếm khoảng 0,02% tổng số ô"],
 ["Kết luận","Bộ dữ liệu CÓ cần tiền xử lý, nhưng mức độ nhẹ. Có thể sửa ở mức ô mà không phải xóa bản ghi nào."]],3800,CW-3800),
PB(),

/* ══ 4 ══ */
new Paragraph({children:[T("4. PHÂN TÍCH ĐƠN BIẾN",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
H2("4.1","Biến số: thống kê mô tả"),
threeColTable([
 ["Age","25,82 · 25 · 4,91","18 – 59 · lệch +0,13 · 34 giá trị"],
 ["Academic Pressure","3,14 · 3 · 1,38","0 – 5 · lệch −0,14 · 6 giá trị"],
 ["CGPA","7,66 · 7,77 · 1,47","0 – 10 · lệch −0,11 · 332 giá trị"],
 ["Study Satisfaction","2,94 · 3 · 1,36","0 – 5 · lệch +0,01 · 6 giá trị"],
 ["Work/Study Hours","7,16 · 8 · 3,71","0 – 12 · lệch −0,46 · 13 giá trị"],
 ["Financial Stress","3,14 · 3 · 1,44","1 – 5 · lệch −0,13 · 5 giá trị"],
 ["Work Pressure","0,000 · 0 · 0,044","0 – 5 · lệch +108,6 · gần như hằng số"],
 ["Job Satisfaction","0,001 · 0 · 0,044","0 – 4 · lệch +74,1 · gần như hằng số"],
],[2400,2300,CW-4700],["Biến","TB · Trung vị · Độ lệch chuẩn","Khoảng · Độ lệch · Số giá trị"]),
body("Nhận xét: sáu biến số có ý nghĩa đều có độ lệch gần 0 (trong khoảng −0,46 đến +0,13), nghĩa là phân bố khá cân đối, không cần biến đổi logarit. Hai biến Work Pressure và Job Satisfaction có độ lệch cực lớn (108,6 và 74,1) — đây là dấu hiệu toán học của cột gần như hằng số, khớp với phát hiện ở mục 3.2."),
H2("4.2","Phân bố bốn biến số chính"),
...img(IMG("e1_phanbo"),6.6,3.95,"Hình 1. Phân bố của Tuổi, Điểm CGPA, Số giờ học/làm và Áp lực học tập"),
body("Ba điểm đáng chú ý. Thứ nhất, phân bố tuổi tập trung trong khoảng 18–34, phần đuôi kéo dài tới 59 chỉ gồm 12 sinh viên — phân vị 99% của tuổi là 34. Thứ hai, điểm CGPA tập trung trong khoảng 5–10, hoàn toàn không có giá trị trong khoảng 0,01–5, ngoại trừ 9 giá trị bằng đúng 0 — củng cố nhận định rằng các số 0 đó là giá trị thiếu bị mã hóa nhầm. Thứ ba, phân bố số giờ học/làm lệch về phía cao: nhóm 10 giờ mỗi ngày đông nhất với 4.234 sinh viên."),
H2("4.3","Phát hiện ngoại lai"),
...img(IMG("e2_ngoailai"),6.6,2.3,"Hình 2. Biểu đồ hộp của sáu biến số, phát hiện ngoại lai theo quy tắc 1,5×IQR"),
threeColTable([
 ["Age","12","0,04%"],["CGPA","9","0,03%"],["Work/Study Hours","0","0%"],
 ["Academic Pressure","0","0%"],["Study Satisfaction","0","0%"],["Financial Stress","0","0%"],
],[2600,1600,CW-4200],["Biến","Số điểm ngoại lai","Tỷ lệ"]),
body("Tổng cộng chỉ 21 điểm ngoại lai trên toàn bộ các biến số có ý nghĩa, chiếm chưa tới 0,1%. Bốn biến dạng thang đo 1–5 và biến số giờ hoàn toàn không có ngoại lai, điều này hợp lý vì chúng bị giới hạn trong khoảng hẹp. 12 ngoại lai của biến Tuổi là sinh viên từ 44 đến 59 tuổi — đây là giá trị hợp lệ về mặt thực tế (sinh viên lớn tuổi), không phải lỗi nhập liệu, nên giữ nguyên. 9 ngoại lai của CGPA chính là 9 giá trị 0 đã nêu, và đây mới là lỗi thật."),
keypt("Bài học phương pháp: ngoại lai thống kê không đồng nghĩa với lỗi dữ liệu. Phải đối chiếu với hiểu biết thực tế mới quyết định được giữ hay sửa."),
H2("4.4","Biến phân loại"),
threeColTable([
 ["Gender","2","Male 55,7% · Female 44,3%"],
 ["Sleep Duration","5","Dưới 5 giờ 29,8% · 7–8 giờ 26,3% · 5–6 giờ 22,2% · Trên 8 giờ 21,7% · Others 0,1%"],
 ["Dietary Habits","4","Unhealthy 37,0% · Moderate 35,6% · Healthy 27,4% · Others 0,04%"],
 ["Suicidal thoughts","2","Yes 63,3% · No 36,7%"],
 ["Family History","2","No 51,6% · Yes 48,4%"],
 ["Degree","28","Class 12 chiếm 21,8%; 27 bằng cấp có từ 100 bản ghi trở lên"],
 ["City","52","Kalyan 5,6%; chỉ 30 giá trị có từ 10 bản ghi trở lên"],
 ["Profession","14","Student 99,89%; 13 nghề còn lại tổng cộng 31 bản ghi"],
],[2200,700,CW-2900],["Biến","Số mức","Phân bố"]),
note("Tỷ lệ 63,3% người trả lời từng có ý định tự tử là rất cao so với quần thể chung. Con số này cần được diễn giải thận trọng: nó phản ánh đặc điểm của mẫu khảo sát, không phải tỷ lệ trong dân số sinh viên nói chung."),
H2("4.5","Biến mục tiêu"),
...img(IMG("c1_target"),5.4,3.15,"Hình 3. Phân bố biến mục tiêu Depression"),
twoColTable([
 ["Có dấu hiệu trầm cảm (1)","16.336 sinh viên — 58,5%"],
 ["Không có dấu hiệu (0)","11.565 sinh viên — 41,5%"],
 ["Tỷ số","1,41 : 1"],
 ["Đánh giá","Mất cân bằng nhẹ. Ngưỡng thường dùng là từ 4:1 trở lên mới cần kỹ thuật lấy mẫu lại, nên bộ dữ liệu này không cần."],
],3600,CW-3600),
note("Lưu ý khi làm tròn: giá trị chính xác là 58,549…%. Làm tròn một lần cho 58,5%. Nếu làm tròn hai lần (58,549 → 58,55 → 58,6) sẽ ra 58,6% — sai 0,1 điểm phần trăm. Đây là lỗi dễ mắc khi chép lại số từ câu trả lời của trợ lý AI."),
PB(),

/* ══ 5 ══ */
new Paragraph({children:[T("5. PHÂN TÍCH HAI BIẾN",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
H2("5.1","Biến số so với biến mục tiêu"),
body("Dùng hệ số tương quan point-biserial (phù hợp khi một biến nhị phân, một biến liên tục) kèm kiểm định t so sánh trung bình hai nhóm."),
threeColTable([
 ["Academic Pressure","+0,475","2,36 → 3,69 · p < 0,001"],
 ["Financial Stress","+0,364","2,52 → 3,58 · p < 0,001"],
 ["Age","−0,226","27,14 → 24,89 · p < 0,001"],
 ["Work/Study Hours","+0,209","6,24 → 7,81 · p < 0,001"],
 ["Study Satisfaction","−0,168","3,22 → 2,75 · p < 0,001"],
 ["CGPA","+0,022","7,62 → 7,68 · p < 0,001"],
 ["Work Pressure","−0,003","0,00 → 0,00 · p = 0,58"],
 ["Job Satisfaction","−0,003","0,00 → 0,00 · p = 0,56"],
],[2500,1500,CW-4000],["Biến","Hệ số r","Trung bình nhóm 0 → nhóm 1"]),
note("Chi tiết kỹ thuật: hệ số của Financial Stress phải tính sau khi loại 3 ô khuyết (n = 27.898). Nếu gọi hàm tương quan trực tiếp trên cột còn khuyết, kết quả trả về NaN. Đây là lỗi dễ bỏ sót vì chương trình không báo lỗi."),
...img(IMG("c2_pressure"),6.6,2.3,"Hình 4. Hai yếu tố áp lực mạnh nhất: quan hệ đơn điệu tăng rõ rệt"),
body("Hai biểu đồ trên cho thấy quan hệ đơn điệu rất rõ. Áp lực học tập từ mức 1 lên mức 5 làm tỷ lệ trầm cảm tăng từ 19,4% lên 86,1% — chênh 67 điểm phần trăm. Áp lực tài chính cùng xu hướng, từ 31,9% lên 81,3%. Đáng chú ý: ngay cả nhóm áp lực tài chính thấp nhất vẫn có gần 32% có dấu hiệu trầm cảm, cho thấy còn nhiều yếu tố khác cùng tác động."),
...img(IMG("c5_age_hours"),6.6,2.3,"Hình 5. Tuổi là yếu tố bảo vệ; cường độ học tập là yếu tố nguy cơ"),
body("Tuổi có quan hệ nghịch: nhóm 18–20 tuổi có tỷ lệ 72,3%, giảm dần còn 40,9% ở nhóm từ 31 tuổi — chênh 31,5 điểm phần trăm. Về cường độ học, nhóm học 10–12 giờ mỗi ngày có tỷ lệ 69,0% so với 41,6% ở nhóm dưới 3 giờ."),
H3("5.1.1","Biểu đồ phân tán: vì sao CGPA không phân biệt được"),
body("Hệ số 0,022 là một con số trừu tượng. Biểu đồ phân tán dưới đây cho thấy trực quan điều đó nghĩa là gì."),
...img(IMG("e5_scatter_cgpa"),6.6,3.7,"Hình 6. Biểu đồ phân tán CGPA × Tuổi, tô màu theo tình trạng trầm cảm"),
body("Nếu CGPA phân biệt được hai nhóm, ta sẽ thấy màu đỏ dồn về một phía của trục hoành. Thực tế hai màu trộn đều từ trái sang phải — đúng với hệ số gần 0. Ngược lại, theo trục tung có thể thấy dải tuổi 18–25 đậm màu đỏ hơn rõ rệt so với dải 28–34, phù hợp với hệ số −0,226 của biến Tuổi. Đây là ví dụ cho thấy biểu đồ phân tán giúp kiểm tra bằng mắt kết quả mà hệ số tương quan đưa ra."),
note("Kỹ thuật vẽ: bộ dữ liệu có gần 28.000 điểm, vẽ hết sẽ thành một mảng đặc không đọc được. Báo cáo lấy mẫu ngẫu nhiên 6.000 điểm, đặt độ trong suốt 28%, và thêm một lượng nhiễu rất nhỏ vào trục tung vì Tuổi là số nguyên nên các điểm xếp chồng thành hàng."),
keypt("Phát hiện đáng chú ý: CGPA có hệ số chỉ +0,022. Dù p < 0,001 (do cỡ mẫu lớn), độ lớn hiệu ứng gần như bằng 0 — kết quả học tập hầu như không liên quan đến trầm cảm trong bộ dữ liệu này."),
H2("5.2","Biến phân loại so với biến mục tiêu"),
body("Dùng kiểm định chi-square kèm hệ số Cramér's V để đo độ mạnh của liên hệ. Chỉ xét các biến có không quá 30 mức."),
threeColTable([
 ["Suicidal thoughts","0,546","8.323,9 · p < 0,001 · tỷ lệ 23,2% → 79,0%"],
 ["Dietary Habits","0,208","1.202,6 · p < 0,001 · tỷ lệ 45,4% → 70,7%"],
 ["Degree","0,138","531,4 · p < 0,001 · tỷ lệ 50,5% → 70,8%"],
 ["Sleep Duration","0,100","276,8 · p < 0,001 · tỷ lệ 50,0% → 64,5%"],
 ["Family History","0,053","79,4 · p < 0,001 · tỷ lệ 56,0% → 61,3%"],
 ["Profession","0,023","14,3 · p = 0,35 · KHÔNG có ý nghĩa thống kê"],
 ["Gender","0,002","0,1 · p = 0,77 · KHÔNG có ý nghĩa thống kê"],
],[2300,1200,CW-3500],["Biến","Cramér's V","Chi-square · p-value · khoảng tỷ lệ"]),
...img(IMG("e3_phanloai"),6.6,1.95,"Hình 7. Tỷ lệ trầm cảm theo bốn biến phân loại quan trọng"),
body("Hình 7 cho thấy ba dạng quan hệ khác nhau. Ý định tự tử tạo khác biệt rất lớn (23,2% so với 79,0%). Chế độ ăn tăng đều theo mức độ kém lành mạnh. Thời lượng ngủ lại KHÔNG đơn điệu: nhóm ngủ 7–8 giờ (59,5%) cao hơn nhóm ngủ 5–6 giờ (56,9%), dù cả hai đều thấp hơn nhóm ngủ dưới 5 giờ. Tiền sử gia đình chỉ tạo chênh lệch 5,3 điểm phần trăm."),
...img(IMG("c4_lifestyle"),6.6,2.3,"Hình 8. Giấc ngủ và dinh dưỡng — hai biến lối sống có thể can thiệp"),
body("Chế độ ăn tăng đều 25,3 điểm phần trăm giữa hai cực. Giấc ngủ thì khác: quan hệ không tuyến tính, nên khi vẽ biểu đồ phải dùng màu trung tính thay vì thang màu chuyển dần, nếu không màu sắc sẽ mâu thuẫn với chiều cao cột."),
H3("5.2.1","Biểu đồ phân tán cấp thành phố"),
body("Một câu hỏi tự nhiên của bước khám phá: tỷ lệ trầm cảm có khác nhau rõ rệt giữa các thành phố không? Biểu đồ phân tán cấp nhóm trả lời nhanh câu hỏi này."),
...img(IMG("e6_scatter_city"),6.6,3.7,"Hình 9. Mỗi chấm là một thành phố — trục hoành là cỡ mẫu, trục tung là tỷ lệ trầm cảm"),
body("Ba mươi thành phố có từ 100 bản ghi trở lên đều nằm trong khoảng 52,4% đến 67,3%, với độ lệch chuẩn chỉ 3,8 điểm phần trăm quanh mức trung bình 58,5%. Không có thành phố nào tách hẳn khỏi nhóm. Biểu đồ cũng cho thấy không có quan hệ giữa cỡ mẫu và tỷ lệ — nghĩa là các thành phố ít bản ghi không bị lệch một cách hệ thống."),
keypt("Kết luận về biến City: biến này không mang nhiều thông tin phân biệt, nên không cần đưa vào mô hình. Giá trị của nó chủ yếu nằm ở chỗ 26 ô rác giúp phát hiện lỗi lệch cột trong quy trình nhập liệu."),
keypt("Hai kết quả âm tính đáng báo cáo: Giới tính (p = 0,77) và Nghề nghiệp (p = 0,35) đều KHÔNG có liên hệ với trầm cảm. Kết quả âm tính cũng là kết quả, và trong trường hợp này nó bác bỏ một giả định phổ biến."),
note("Khi diễn giải biến Profession, cần cẩn trọng: khoảng tỷ lệ 58,5%–100% trông rất rộng, nhưng mức 100% đến từ các nhóm nghề chỉ có 1–2 bản ghi. Với cỡ mẫu nhỏ như vậy, tỷ lệ không có ý nghĩa."),
H2("5.3","Tương quan giữa các biến độc lập"),
...img(IMG("e4_tuongquan"),5.9,4.8,"Hình 10. Ma trận tương quan giữa các biến số chính"),
body("Kiểm tra đa cộng tuyến là bước bắt buộc trước khi xây mô hình. Kết quả: trong số các biến độc lập có ý nghĩa, không có cặp nào đạt |r| > 0,3. Cặp duy nhất vượt ngưỡng là Work Pressure với Job Satisfaction (r = 0,771), nhưng cả hai đều là cột gần như hằng số và sẽ bị loại ở bước tiền xử lý, nên không gây vấn đề."),
H3("5.3.1","Bảng xếp hạng tổng hợp"),
...img(IMG("c3_corr"),6.0,3.4,"Hình 11. Xếp hạng toàn bộ yếu tố theo hệ số tương quan với biến mục tiêu"),
body("Hình 11 tổng hợp kết quả của cả mục 5.1 và 5.2 trên một trục chung, cho phép so sánh trực tiếp sức mạnh của mọi yếu tố. Ba yếu tố dẫn đầu là ý định tự tử, áp lực học tập và áp lực tài chính. Hai yếu tố cuối bảng — điểm CGPA và giới tính — gần như bằng 0."),
keypt("Kết luận: bộ dữ liệu không có vấn đề đa cộng tuyến. Các biến độc lập đo những khía cạnh khác nhau, nên có thể đưa đồng thời vào mô hình mà không lo hệ số bị méo."),
PB(),

/* ══ 6 ══ */
new Paragraph({children:[T("6. NHẬN ĐỊNH VÀ ĐỀ XUẤT BƯỚC TIẾP THEO",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
H2("6.1","Năm nhận định chính"),
threeColTable([
 ["1","Dữ liệu sạch ở bề mặt, bẩn ở chi tiết","Không khuyết, không trùng, nhưng có 122 ô cần can thiệp thuộc bốn nhóm vấn đề khác nhau."],
 ["2","Ba cột không mang thông tin","Profession, Work Pressure và Job Satisfaction gần như hằng số do 99,9% mẫu là sinh viên."],
 ["3","Yếu tố hoàn cảnh vượt trội","Áp lực học tập (0,475) và tài chính (0,364) mạnh hơn hẳn tiền sử gia đình (0,053)."],
 ["4","Học lực không liên quan","CGPA có hệ số 0,022 — gần như bằng 0 dù p < 0,001."],
 ["5","Không khác biệt giới tính","Nam 58,6% so với nữ 58,5%, p = 0,77."],
],[600,2700,CW-3300],["#","Nhận định","Căn cứ"]),
H2("6.2","Đề xuất xử lý trước khi phân tích sâu"),
threeColTable([
 ["1","Loại 4 cột","id, Profession, Work Pressure, Job Satisfaction"],
 ["2","Làm sạch cột City","Giữ 30 thành phố có từ 10 bản ghi; 26 giá trị rác chuyển thành khuyết"],
 ["3","Chuẩn hóa thang đo","28 giá trị ngoài thang chuyển thành khuyết"],
 ["4","Xử lý nhãn rác","65 nhãn “Others” chuyển thành khuyết"],
 ["5","Điền khuyết","Trung vị cho biến số, giá trị phổ biến nhất cho biến phân loại"],
 ["6","Mã hóa biến","Thời lượng ngủ → số giờ; Chế độ ăn → thang 1–3; Yes/No → 1/0"],
],[600,2200,CW-2800],["#","Bước","Chi tiết"]),
H2("6.3","Hướng phân tích đáng theo đuổi"),
bull("Phân tích tương tác: hai yếu tố nguy cơ khi xuất hiện cùng lúc có cộng hưởng không? Gợi ý bắt đầu từ cặp Áp lực học tập × Ý định tự tử."),
bull("Xây chỉ số tổng hợp đếm số yếu tố nguy cơ đồng thời, kiểm tra xem nó dự báo tốt hơn từng yếu tố riêng lẻ không."),
bull("Phân tích theo nhóm tuổi để xác định nhóm sinh viên dễ tổn thương nhất."),
bull("Kiểm tra độ ổn định: chia dữ liệu theo giới tính, nhóm tuổi, chế độ ăn và tính lại các hệ số để xem phát hiện có vững không."),
bull("Xây mô hình dự báo (hồi quy logistic) — không nhằm chẩn đoán, mà để kiểm chứng mức độ nhất quán của các mối liên hệ đã tìm thấy."),
PB(),

/* ══ 7 ══ */
new Paragraph({children:[T("7. HẠN CHẾ CỦA BƯỚC KHÁM PHÁ",{size:SZ_H1,bold:true,color:C.white})],
 shading:{fill:C.headBg,type:ShadingType.CLEAR},spacing:{before:0,after:160},outlineLevel:0}),
threeColTable([
 ["Tương quan không phải nhân quả","Dữ liệu cắt ngang, thu tại một thời điểm","Không thể biết áp lực học tập gây trầm cảm, hay trầm cảm khiến sinh viên cảm nhận áp lực nặng hơn."],
 ["Biến mục tiêu là sàng lọc","Nhãn Depression đến từ tự báo cáo","Không phải chẩn đoán lâm sàng của bác sĩ. Tỷ lệ 58,5% không phải tỷ lệ mắc bệnh."],
 ["Mẫu không đại diện","Không rõ cách lấy mẫu","Tỷ lệ 63,3% từng có ý định tự tử cho thấy mẫu có thể lệch về nhóm có vấn đề tâm lý."],
 ["Giới hạn bối cảnh","Khảo sát tại Ấn Độ","Không suy rộng trực tiếp cho sinh viên Việt Nam nếu chưa khảo sát lại."],
 ["Cỡ mẫu lớn làm p-value mất ý nghĩa","n ≈ 28.000","Gần như mọi khác biệt đều “có ý nghĩa thống kê”. Phải đọc độ lớn hiệu ứng, không chỉ p-value."],
 ["Chưa kiểm tra tương tác","Báo cáo này chỉ phân tích một và hai biến","Quan hệ ba biến trở lên có thể đảo ngược kết luận — cần phân tích tiếp."],
],[2500,1900,CW-4400],["Hạn chế","Nguyên nhân","Hệ quả khi diễn giải"]),
sp(160),
keypt("Kết luận chung: bộ dữ liệu đủ chất lượng để phân tích sâu sau khi thực hiện sáu bước tiền xử lý ở mục 6.2. Các mối liên hệ tìm được trong bước khám phá đủ mạnh và nhất quán để đáng theo đuổi, nhưng mọi kết luận phải diễn đạt dưới dạng liên hệ, không phải nhân quả."),
sp(200),
new Paragraph({children:[T("HẾT BÁO CÁO",{size:SZ_H1,bold:true,color:C.white})],
 alignment:AlignmentType.CENTER,shading:{fill:C.headBg,type:ShadingType.CLEAR},
 spacing:{before:200,after:200}}),
]}]});
const OUT=process.argv[2]||"/tmp/eda.docx";
Packer.toBuffer(doc).then(b=>{fs.writeFileSync(OUT,b);console.log("Done →",OUT);});
