const B=require("./base.js"); const {baiTap,capHeading,PB,sp}=B;
const SD_G="student_depression_GOC.csv", SD_C="student_depression_CLEANED.csv";
const AS_G="asd_treEm_GOC.csv", AS_C="asd_treEm_CLEANED.csv";
module.exports=[
...capHeading("1","CƠ BẢN — Làm quen với dữ liệu và với AI",
 "Năm bài đầu không đòi hỏi kiến thức thống kê. Mục tiêu là bạn mở được tệp dữ liệu, đặt được câu hỏi đúng cho AI, và quan trọng nhất — hình thành thói quen chạy lại mã để kiểm chứng mọi con số.","000000"),

...baiTap({id:"1",ten:"Mô tả bộ dữ liệu",cap:"Cơ bản",duLieu:SD_G,thoiGian:"30 phút",
 boiCanh:"Bạn vừa nhận một tệp dữ liệu lạ. Việc đầu tiên luôn là trả lời câu hỏi “trong tay mình đang có gì”.",
 yeuCau:[
  "Tải tệp lên một trợ lý AI (ChatGPT, Gemini hoặc Claude), yêu cầu cho biết số dòng và số cột.",
  "Lập bảng mô tả từng cột gồm ba thông tin: tên cột, kiểu dữ liệu (số hay chữ), ý nghĩa bạn hiểu.",
  "Đếm xem có bao nhiêu cột kiểu số và bao nhiêu cột kiểu chữ.",
  "Yêu cầu AI viết mã Python in ra các con số trên, rồi tự chạy lại và đối chiếu.",
 ],
 sanPham:"Một bảng mô tả đầy đủ 18 biến, kèm đoạn mã Python và ảnh chụp kết quả khi bạn chạy.",
 goiY:"Câu lệnh gợi ý: “Tệp đính kèm có bao nhiêu dòng, bao nhiêu cột? Liệt kê từng cột kèm kiểu dữ liệu. Viết kèm mã pandas để tôi chạy lại.”",
 diem:[["Bảng mô tả đủ 18 biến, ý nghĩa hợp lý","4"],["Phân loại đúng kiểu dữ liệu từng cột","2"],
       ["Có mã Python và kết quả chạy thật","3"],["Trình bày rõ ràng, không lỗi chính tả","1"]]}),
PB(),

...baiTap({id:"2",ten:"Đếm giá trị khuyết và bản ghi trùng",cap:"Cơ bản",duLieu:`${SD_G} và ${AS_G}`,thoiGian:"30 phút",
 boiCanh:"Hai bộ dữ liệu này nhìn bề ngoài giống nhau, nhưng một bộ rất sạch còn bộ kia có vấn đề nghiêm trọng. Bài tập giúp bạn thấy sự khác biệt.",
 yeuCau:[
  "Với mỗi bộ, đếm tổng số ô khuyết và cho biết chúng nằm ở cột nào.",
  "Với mỗi bộ, đếm số dòng trùng lặp hoàn toàn. Lưu ý: phải bỏ cột mã định danh trước khi so sánh, nếu không sẽ không bao giờ tìm thấy dòng trùng.",
  "So sánh hai bộ và nhận xét bộ nào sạch hơn, kèm con số chứng minh.",
  "Với bộ có nhiều dòng trùng, tính tỷ lệ phần trăm số dòng trùng trên tổng số dòng.",
 ],
 sanPham:"Bảng so sánh hai bộ dữ liệu theo bốn chỉ số: số dòng, số ô khuyết, số dòng trùng, tỷ lệ trùng.",
 goiY:"Trong pandas, bỏ cột định danh rồi mới gọi phương thức kiểm tra trùng. Nếu quên bước này, kết quả sẽ luôn bằng 0 vì mỗi dòng có mã riêng.",
 diem:[["Đếm đúng ô khuyết của cả hai bộ","2,5"],["Đếm đúng dòng trùng, có bỏ cột định danh","3"],
       ["Tính đúng tỷ lệ phần trăm","1,5"],["Nhận xét so sánh có căn cứ số liệu","3"]]}),
PB(),

...baiTap({id:"3",ten:"Tính tỷ lệ biến mục tiêu",cap:"Cơ bản",duLieu:SD_G,thoiGian:"20 phút",
 boiCanh:"Biến mục tiêu là biến bạn muốn giải thích. Tỷ lệ của nó quyết định bạn có phải xử lý mất cân bằng dữ liệu hay không.",
 yeuCau:[
  "Đếm số sinh viên có và không có dấu hiệu trầm cảm (cột Depression).",
  "Tính tỷ lệ phần trăm cho mỗi nhóm, làm tròn một chữ số thập phân.",
  "Tính tỷ số giữa nhóm nhiều hơn và nhóm ít hơn.",
  "Tra cứu và giải thích: tỷ số bao nhiêu thì bị coi là mất cân bằng nghiêm trọng? Bộ dữ liệu này có cần xử lý không?",
 ],
 sanPham:"Bốn con số (hai số đếm, hai tỷ lệ phần trăm), tỷ số, và một đoạn ba câu kết luận về mức mất cân bằng.",
 goiY:"Cẩn thận khi làm tròn. Hãy tính ra đủ chữ số rồi mới làm tròn một lần duy nhất — làm tròn hai lần sẽ cho kết quả sai.",
 diem:[["Đếm đúng số lượng hai nhóm","2"],["Tính và làm tròn đúng tỷ lệ phần trăm","3"],
       ["Tính đúng tỷ số","2"],["Kết luận về mất cân bằng có căn cứ","3"]]}),
PB(),

...baiTap({id:"4",ten:"Biểu đồ đầu tiên",cap:"Cơ bản",duLieu:SD_C,thoiGian:"45 phút",
 boiCanh:"Một biểu đồ tốt nói được điều mà bảng số phải đọc rất lâu mới nhận ra. Bài này bạn vẽ biểu đồ đầu tiên và áp dụng ngay các nguyên tắc trình bày.",
 yeuCau:[
  "Tính tỷ lệ trầm cảm cho từng mức của biến Áp lực học tập (thang 1 đến 5).",
  "Nhờ AI viết mã matplotlib vẽ biểu đồ cột thể hiện năm tỷ lệ này.",
  "Bắt buộc có: tiêu đề nêu kết luận (không nêu tên loại biểu đồ), nhãn phần trăm ghi trực tiếp trên đầu cột, trục tung bắt đầu từ 0, nhãn tiếng Việt có dấu hiển thị đúng.",
  "Viết một câu mô tả xu hướng bạn nhìn thấy.",
 ],
 sanPham:"Tệp ảnh biểu đồ, đoạn mã đã dùng, và một câu nhận xét xu hướng.",
 goiY:"Nếu chữ tiếng Việt hiện thành ô vuông, hãy chỉ định font DejaVu Sans hoặc Arial trong mã. Số thập phân nên dùng dấu phẩy theo chuẩn Việt Nam.",
 diem:[["Tính đúng năm tỷ lệ","3"],["Biểu đồ có đủ bốn yêu cầu bắt buộc","4"],
       ["Tiêu đề nêu kết luận, không nêu loại biểu đồ","2"],["Nhận xét xu hướng đúng","1"]]}),
PB(),

...baiTap({id:"5",ten:"Bắt lỗi AI đọc sai số",cap:"Cơ bản",duLieu:SD_G,thoiGian:"30 phút",
 boiCanh:"Đây là bài quan trọng nhất của cấp Cơ bản. Trợ lý AI thường đọc lướt tệp lớn rồi ước lượng, và con số nó đưa ra có thể sai ở chữ số thập phân — đủ để làm hỏng độ tin cậy của cả bài báo cáo.",
 yeuCau:[
  "Hỏi AI năm câu hỏi về số liệu của bộ dữ liệu, ví dụ: tỷ lệ trầm cảm, tuổi trung bình, điểm CGPA trung bình, số sinh viên nam, số thành phố khác nhau.",
  "Ghi lại nguyên văn con số AI trả lời cho từng câu.",
  "Tự viết mã Python tính lại cả năm con số đó.",
  "Lập bảng ba cột: con số AI nói — con số bạn chạy ra — khớp hay lệch. Nếu lệch, ghi rõ lệch bao nhiêu.",
  "Viết một đoạn ngắn nêu bạn rút ra điều gì.",
 ],
 sanPham:"Bảng đối chiếu năm con số và một đoạn nhận xét từ 3 đến 5 câu.",
 goiY:"Nếu cả năm con số đều khớp, đừng kết luận vội là AI luôn đúng. Hãy thử hỏi lại cùng câu hỏi trong một phiên chat mới và xem AI có trả lời y hệt không.",
 diem:[["Hỏi đủ năm câu và ghi lại nguyên văn","2"],["Mã Python tính lại đúng cả năm","4"],
       ["Bảng đối chiếu đầy đủ, nêu rõ mức lệch","2"],["Nhận xét thể hiện hiểu vấn đề","2"]]}),
PB(),

...capHeading("2","TRUNG BÌNH — Kỹ năng cốt lõi",
 "Năm bài tiếp theo là những kỹ năng bạn sẽ dùng trong mọi bài phân tích: săn lỗi dữ liệu, xây quy trình làm sạch, so sánh giữa các nhóm và xếp hạng yếu tố. Cần biết dùng pandas ở mức cơ bản.","000000"),

...baiTap({id:"6",ten:"Săn giá trị lạc chỗ",cap:"Trung bình",duLieu:SD_G,thoiGian:"45 phút",
 boiCanh:"Bộ dữ liệu này gần như không có ô khuyết và không có dòng trùng, nên rất dễ bị coi là sạch. Nhưng có một cột chứa những giá trị hoàn toàn không thuộc về nó.",
 yeuCau:[
  "Với mỗi cột phân loại, liệt kê toàn bộ giá trị xuất hiện dưới 10 lần.",
  "Xác định cột nào chứa giá trị lạc chỗ và liệt kê đầy đủ các giá trị đó.",
  "Phân loại các giá trị rác tìm được thành các nhóm (gợi ý: có ít nhất ba nhóm khác nhau).",
  "Suy luận: nhìn vào các giá trị rác, bạn đoán quy trình thu thập dữ liệu đã mắc lỗi gì?",
  "Đề xuất cách xử lý và nêu lý do vì sao chọn cách đó thay vì xóa dòng.",
 ],
 sanPham:"Danh sách đầy đủ giá trị rác, bảng phân loại theo nhóm, một đoạn suy luận về nguyên nhân, và phương án xử lý.",
 goiY:"Hai giá trị “Less Delhi” và “Less than 5 Kalyan” là manh mối quan trọng nhất. Hãy đối chiếu chúng với các giá trị trong cột Sleep Duration.",
 diem:[["Liệt kê đúng và đủ giá trị rác","3"],["Phân loại thành các nhóm hợp lý","2"],
       ["Suy luận đúng nguyên nhân lỗi hệ thống","3"],["Phương án xử lý có lập luận","2"]]}),
PB(),

...baiTap({id:"7",ten:"Xây quy trình tiền xử lý hoàn chỉnh",cap:"Trung bình",duLieu:SD_G,thoiGian:"90 phút",
 boiCanh:"Đây là bài tổng hợp của cấp Trung bình. Bạn sẽ đi từ tệp gốc đến tệp sạch, và quan trọng không kém — ghi lại nhật ký để người khác kiểm tra được.",
 yeuCau:[
  "Rà soát bộ dữ liệu theo đủ bảy nhóm lỗi đã học, báo cáo từng nhóm có hay không.",
  "Tìm các cột gần như hằng số (một giá trị chiếm trên 95% số dòng) và quyết định giữ hay bỏ, kèm lý do.",
  "Tìm các giá trị nằm ngoài thang đo hợp lý và các nhãn rác dạng “Others”.",
  "Thực hiện làm sạch, cố gắng giữ nguyên 100% số dòng.",
  "Ghi nhật ký tiền xử lý theo mẫu: số thứ tự bước, thao tác, lý do, số ô hoặc dòng bị ảnh hưởng.",
  "Xuất tệp đã làm sạch và báo cáo kích thước trước — sau.",
 ],
 sanPham:"Tệp dữ liệu đã làm sạch, mã Python đầy đủ, và bảng nhật ký tiền xử lý.",
 goiY:"Nguyên tắc: chỉ xóa dòng khi bản ghi hỏng quá nặng hoặc trùng lặp. Với lỗi ở mức ô, hãy chuyển thành khuyết rồi điền lại bằng trung vị hoặc giá trị phổ biến nhất.",
 diem:[["Rà soát đủ bảy nhóm lỗi","2"],["Phát hiện đúng các cột gần như hằng số","2"],
       ["Mã làm sạch chạy được, kết quả đúng","3"],["Nhật ký đầy đủ, có lý do cho từng bước","2"],
       ["Giữ được 100% số dòng","1"]]}),
PB(),

...baiTap({id:"8",ten:"So sánh giữa các nhóm và kiểm định",cap:"Trung bình",duLieu:SD_C,thoiGian:"60 phút",
 boiCanh:"Thấy hai nhóm có tỷ lệ khác nhau là một chuyện; chứng minh khác biệt đó không do ngẫu nhiên lại là chuyện khác. Bài này giới thiệu kiểm định chi-square.",
 yeuCau:[
  "Tính tỷ lệ trầm cảm theo từng nhóm chế độ ăn (lành mạnh, trung bình, kém lành mạnh), kèm cỡ mẫu mỗi nhóm.",
  "Thực hiện kiểm định chi-square để xem khác biệt có ý nghĩa thống kê hay không.",
  "Tính hệ số Cramér's V để đo độ mạnh của mối liên hệ. Tra cứu ngưỡng diễn giải của hệ số này.",
  "Lặp lại cả ba bước trên với biến Giới tính. So sánh kết quả hai biến.",
  "Viết kết luận, chú ý dùng đúng từ ngữ: “liên quan đến” chứ không phải “gây ra”.",
 ],
 sanPham:"Bảng kết quả cho hai biến gồm tỷ lệ từng nhóm, giá trị chi-square, p-value, Cramér's V; kèm đoạn kết luận.",
 goiY:"Một kết quả có p rất nhỏ chưa chắc đã quan trọng. Với cỡ mẫu gần 28.000, gần như mọi khác biệt đều “có ý nghĩa thống kê” — vì vậy phải xem thêm Cramér's V để biết liên hệ mạnh hay yếu.",
 diem:[["Tính đúng tỷ lệ và cỡ mẫu từng nhóm","2"],["Chạy đúng kiểm định chi-square","2"],
       ["Tính và diễn giải đúng Cramér's V","3"],["So sánh hai biến có căn cứ","2"],
       ["Dùng đúng từ ngữ, không suy diễn nhân quả","1"]]}),
PB(),

...baiTap({id:"9",ten:"Bộ biểu đồ đồng bộ",cap:"Trung bình",duLieu:SD_C,thoiGian:"90 phút",
 boiCanh:"Bốn biểu đồ rời rạc mỗi cái một kiểu trông như bốn người khác nhau vẽ. Bài này rèn tư duy hệ thống trong thiết kế.",
 yeuCau:[
  "Vẽ bốn biểu đồ cho bốn câu hỏi khác nhau, dùng ít nhất hai loại biểu đồ khác nhau.",
  "Thiết lập một quy ước thiết kế chung và ghi lại thành văn bản: bảng màu, cỡ chữ tiêu đề, cỡ chữ nhãn, cách ghi nhãn giá trị, cách định dạng số thập phân.",
  "Áp dụng quy ước đó cho cả bốn biểu đồ.",
  "Kiểm tra lại: nếu một biến có quan hệ không tăng đều, cách tô màu của bạn có khiến người đọc hiểu sai không?",
  "Xuất bốn ảnh và đặt cạnh nhau để tự đánh giá tính đồng bộ.",
 ],
 sanPham:"Bốn tệp ảnh, một bảng quy ước thiết kế, và đoạn tự đánh giá về tính đồng bộ.",
 goiY:"Hãy thử vẽ biểu đồ tỷ lệ trầm cảm theo Thời lượng ngủ. Quan hệ ở đây không tăng đều — nếu bạn tô màu từ đỏ sang xanh theo số giờ ngủ, màu sẽ nói một đằng còn chiều cao cột nói một nẻo.",
 diem:[["Bốn biểu đồ đúng dữ liệu, dùng ít nhất hai loại","3"],["Bảng quy ước thiết kế rõ ràng","2"],
       ["Bốn biểu đồ tuân thủ nhất quán quy ước","3"],["Phát hiện và xử lý đúng vấn đề màu sắc","2"]]}),
PB(),

...baiTap({id:"10",ten:"Xếp hạng toàn bộ yếu tố",cap:"Trung bình",duLieu:SD_C,thoiGian:"75 phút",
 boiCanh:"Khi có hơn mười biến, câu hỏi tự nhiên là biến nào quan trọng nhất. Bài này cho bạn công cụ trả lời, và cả một phát hiện đi ngược trực giác.",
 yeuCau:[
  "Tính hệ số tương quan point-biserial giữa biến Depression và mọi biến số trong bộ dữ liệu.",
  "Xếp hạng các biến theo giá trị tuyệt đối của hệ số, từ mạnh đến yếu.",
  "Ghi kèm p-value và đánh dấu những biến không có ý nghĩa thống kê (p lớn hơn 0,05).",
  "Vẽ biểu đồ cột ngang thể hiện bảng xếp hạng, dùng hai màu để phân biệt tương quan dương và âm.",
  "Chỉ ra ít nhất hai kết quả đi ngược lại điều bạn nghĩ trước khi làm bài, và bình luận ý nghĩa của chúng.",
 ],
 sanPham:"Bảng xếp hạng đầy đủ, biểu đồ cột ngang, và đoạn bình luận về các kết quả bất ngờ.",
 goiY:"Hãy chú ý kỹ hai biến: Điểm CGPA và Giới tính. Kết quả của chúng có thể khiến bạn ngạc nhiên, và đó chính là chất liệu cho phần bình luận.",
 diem:[["Tính đúng hệ số cho toàn bộ biến số","3"],["Xếp hạng đúng theo trị tuyệt đối","1"],
       ["Có p-value và đánh dấu biến không ý nghĩa","2"],["Biểu đồ phân biệt được dấu của hệ số","2"],
       ["Bình luận đúng về ít nhất hai kết quả bất ngờ","2"]]}),
PB(),
];
