const B=require("./base.js"); const {baiTap,capHeading,PB}=B;
const SD_G="student_depression_GOC.csv", SD_C="student_depression_CLEANED.csv";
const AS_G="asd_treEm_GOC.csv", AS_C="asd_treEm_CLEANED.csv";
module.exports=[
...capHeading("3","NÂNG CAO — Tư duy phản biện với dữ liệu",
 "Năm bài này dạy điều khó nhất: nghi ngờ đúng chỗ. Bạn sẽ học cách phát hiện những lỗi mà mắt thường và cả AI đều bỏ qua — biến nhân bản, rò rỉ nhãn, và kết quả chỉ đúng trên một phần dữ liệu.","000000"),

...baiTap({id:"11",ten:"Phát hiện biến nhân bản",cap:"Nâng cao",duLieu:AS_C,thoiGian:"75 phút",
 boiCanh:"Bộ dữ liệu trẻ tự kỷ có bảy cột ghi nhận bảy rối loạn đi kèm khác nhau: chậm nói, khó học, chậm phát triển trí tuệ, vấn đề hành vi, lo âu, trầm cảm, rối loạn gen. Nhìn qua đây là mỏ vàng để nghiên cứu bệnh đi kèm. Hãy kiểm tra trước khi phân tích.",
 yeuCau:[
  "Tính ma trận tương quan giữa bảy biến rối loạn đi kèm. Báo cáo hệ số nhỏ nhất và lớn nhất trong các cặp.",
  "Với từng cặp biến, tính tỷ lệ phần trăm số trẻ có cùng giá trị ở cả hai biến.",
  "Tính tổng số rối loạn của mỗi trẻ (từ 0 đến 7) và vẽ biểu đồ phân bố của tổng này.",
  "Tính tỷ lệ trẻ rơi vào hai cực: có cả bảy, hoặc không có cái nào.",
  "Dựa trên kiến thức thực tế về y học, lập luận xem bảy chẩn đoán độc lập có thể trùng nhau ở mức này không.",
  "Kết luận: bảy cột này có dùng được để nghiên cứu bệnh đi kèm không? Nếu không thì vì sao?",
 ],
 sanPham:"Ma trận tương quan, bảng tỷ lệ trùng khớp từng cặp, biểu đồ phân bố, và một đoạn lập luận kết luận.",
 goiY:"Hãy tự hỏi: tỷ lệ mắc chậm nói và tỷ lệ mắc rối loạn gen trong thực tế có giống nhau không? Nếu hai bệnh hoàn toàn khác nhau mà dữ liệu cho thấy chúng luôn đi cùng nhau, điều đó nói lên gì về dữ liệu chứ không phải về bệnh?",
 diem:[["Ma trận tương quan đúng, báo cáo min–max","2"],["Tính đúng tỷ lệ trùng khớp từng cặp","2"],
       ["Biểu đồ phân bố và tỷ lệ hai cực","2"],["Lập luận y học thuyết phục","2"],
       ["Kết luận đúng và nêu được hệ quả","2"]]}),
PB(),

...baiTap({id:"12",ten:"Phát hiện rò rỉ nhãn",cap:"Nâng cao",duLieu:AS_C,thoiGian:"75 phút",
 boiCanh:"Bạn xây một mô hình dự báo trẻ có dấu hiệu tự kỷ dựa trên 10 mục sàng lọc A1–A10. Mô hình đạt độ chính xác gần như tuyệt đối. Trước khi mừng, hãy kiểm tra.",
 yeuCau:[
  "Tính tổng điểm sàng lọc AQ (cộng mười mục A1 đến A10) cho từng trẻ.",
  "Lập bảng chéo giữa tổng điểm AQ và nhãn ASD_traits.",
  "Đếm xem có bao nhiêu trẻ không mang nhãn ASD nhưng lại có tổng điểm từ 4 trở lên.",
  "Từ bảng chéo, suy ra quy tắc gán nhãn. Quy tắc đó có ngoại lệ nào không?",
  "Giải thích vì sao việc dùng A1–A10 để dự báo nhãn là lập luận vòng tròn.",
  "Đề xuất: trong bộ dữ liệu này, câu hỏi nghiên cứu nào VẪN trả lời được một cách hợp lệ?",
 ],
 sanPham:"Bảng chéo đầy đủ, con số đếm, phát biểu quy tắc gán nhãn, và danh sách ít nhất ba câu hỏi vẫn hợp lệ.",
 goiY:"Dấu hiệu nhận biết rò rỉ nhãn: một ô trong bảng chéo bằng đúng 0 ở nơi lẽ ra phải có vài trường hợp. Về câu hỏi cuối, hãy nghĩ tới những biến được ghi nhận độc lập với quá trình chấm điểm, ví dụ tuổi hay người thực hiện sàng lọc.",
 diem:[["Tính đúng tổng điểm AQ","1,5"],["Bảng chéo đúng và đầy đủ","2"],
       ["Đếm đúng số ngoại lệ","1,5"],["Phát biểu đúng quy tắc gán nhãn","2"],
       ["Giải thích được lập luận vòng tròn","1,5"],["Đề xuất được câu hỏi vẫn hợp lệ","1,5"]]}),
PB(),

...baiTap({id:"13",ten:"Phân tích tương tác giữa hai yếu tố",cap:"Nâng cao",duLieu:SD_C,thoiGian:"75 phút",
 boiCanh:"Hai yếu tố nguy cơ khi xuất hiện cùng lúc có thể chỉ cộng lại, nhưng cũng có thể cộng hưởng — nghĩa là tác động chung lớn hơn tổng hai tác động riêng. Phân biệt hai trường hợp này rất quan trọng khi thiết kế biện pháp can thiệp.",
 yeuCau:[
  "Lập bảng chéo tỷ lệ trầm cảm theo hai biến cùng lúc: Áp lực học tập (5 mức) và Ý định tự tử (có/không).",
  "Vẽ biểu đồ nhiệt thể hiện bảng này, ghi giá trị phần trăm trực tiếp trong từng ô.",
  "Xác định ô có tỷ lệ thấp nhất và ô có tỷ lệ cao nhất, tính tỷ số giữa chúng.",
  "Tính xem ở mức áp lực thấp nhất, việc có ý định tự tử làm tăng tỷ lệ thêm bao nhiêu điểm phần trăm. Làm tương tự ở mức áp lực cao nhất.",
  "So sánh hai mức tăng đó và kết luận: đây là hiệu ứng cộng dồn hay cộng hưởng? Chú ý hiện tượng chạm trần.",
  "Rút ra một hàm ý cho việc sàng lọc sinh viên có nguy cơ.",
 ],
 sanPham:"Bảng chéo, biểu đồ nhiệt, các con số tính toán, và đoạn kết luận kèm hàm ý thực tiễn.",
 goiY:"Khi một tỷ lệ đã gần 95%, nó không thể tăng thêm nhiều nữa dù yếu tố nguy cơ mạnh đến đâu. Hiện tượng này gọi là chạm trần, và nó khiến việc so sánh mức tăng tuyệt đối trở nên khó diễn giải.",
 diem:[["Bảng chéo đúng","2"],["Biểu đồ nhiệt có nhãn giá trị trong ô","2"],
       ["Tính đúng tỷ số hai cực","1,5"],["Tính đúng mức tăng ở hai đầu thang","2"],
       ["Kết luận có xét hiện tượng chạm trần","1,5"],["Hàm ý thực tiễn hợp lý","1"]]}),
PB(),

...baiTap({id:"14",ten:"Xây chỉ số tổng hợp và đường liều – đáp ứng",cap:"Nâng cao",duLieu:SD_C,thoiGian:"90 phút",
 boiCanh:"Từng yếu tố nguy cơ riêng lẻ chỉ giải thích được một phần. Nhưng khi đếm số yếu tố mà một người cùng lúc mắc phải, bức tranh trở nên rất rõ — và rất dễ áp dụng trong thực tế.",
 yeuCau:[
  "Chọn năm yếu tố nguy cơ nhị phân, ví dụ: áp lực học tập cao (từ 4 trở lên), áp lực tài chính cao, ngủ dưới 5 giờ, ăn uống kém lành mạnh, từng có ý định tự tử.",
  "Với mỗi sinh viên, đếm số yếu tố nguy cơ mắc phải, cho ra một chỉ số từ 0 đến 5.",
  "Tính tỷ lệ trầm cảm cho từng giá trị của chỉ số, kèm cỡ mẫu.",
  "Vẽ biểu đồ cột thể hiện quan hệ này, ghi cỡ mẫu dưới mỗi cột.",
  "Tính tỷ số giữa nhóm cao nhất và nhóm thấp nhất.",
  "So sánh sức mạnh dự báo của chỉ số tổng hợp với từng yếu tố riêng lẻ. Chỉ số tổng hợp có tốt hơn không?",
  "Thiết kế một phiếu sàng lọc năm câu hỏi dựa trên chỉ số này, kèm ngưỡng phân tầng hành động.",
 ],
 sanPham:"Bảng tỷ lệ theo chỉ số, biểu đồ cột, so sánh với yếu tố đơn lẻ, và một phiếu sàng lọc hoàn chỉnh.",
 goiY:"Khi so sánh sức mạnh dự báo, hãy dùng cùng một thước đo cho cả chỉ số tổng hợp lẫn từng yếu tố riêng, ví dụ hệ số tương quan hoặc AUC. So sánh bằng cảm tính sẽ không thuyết phục.",
 diem:[["Xây đúng chỉ số tổng hợp","2"],["Bảng tỷ lệ và cỡ mẫu đầy đủ","2"],
       ["Biểu đồ đúng, có ghi cỡ mẫu","1,5"],["So sánh với yếu tố đơn lẻ bằng thước đo chung","2"],
       ["Phiếu sàng lọc có ngưỡng phân tầng hợp lý","2,5"]]}),
PB(),

...baiTap({id:"15",ten:"Kiểm tra độ ổn định của phát hiện",cap:"Nâng cao",duLieu:SD_C,thoiGian:"75 phút",
 boiCanh:"Một phát hiện đúng trên toàn bộ dữ liệu chưa chắc đúng trên từng nhóm nhỏ. Nếu nó chỉ đúng ở một nhóm, kết luận chung của bạn đang che giấu sự thật.",
 yeuCau:[
  "Chọn phát hiện mạnh nhất từ Bài 10, ví dụ quan hệ giữa áp lực học tập và trầm cảm.",
  "Chia dữ liệu theo giới tính, tính lại hệ số tương quan cho từng nhóm. Kết quả có giống nhau không?",
  "Chia dữ liệu theo ba nhóm tuổi, tính lại hệ số cho từng nhóm.",
  "Chia theo chế độ ăn, tính lại lần nữa.",
  "Lập bảng tổng hợp mọi cách chia, kèm cỡ mẫu từng nhóm con.",
  "Kết luận phát hiện có ổn định không. Nếu có nhóm nào lệch rõ, hãy tìm hiểu vì sao và cân nhắc cỡ mẫu của nhóm đó.",
 ],
 sanPham:"Bảng tổng hợp hệ số theo mọi cách chia kèm cỡ mẫu, và đoạn kết luận về độ ổn định.",
 goiY:"Khi chia nhỏ, cỡ mẫu giảm nên hệ số dao động nhiều hơn. Đừng vội kết luận một nhóm khác biệt chỉ vì hệ số lệch một chút — hãy xem nhóm đó có bao nhiêu quan sát.",
 diem:[["Chia đúng theo cả ba cách","3"],["Tính lại hệ số chính xác cho từng nhóm con","2"],
       ["Bảng tổng hợp đầy đủ, có cỡ mẫu","2"],["Kết luận có xét tới cỡ mẫu nhóm con","3"]]}),
PB(),

...capHeading("4","THỬ THÁCH — Tổng hợp và phản biện",
 "Ba bài cuối không có đáp án duy nhất. Chúng mô phỏng công việc thật: bạn nhận một bài phân tích và phải đánh giá nó, hoặc tự làm trọn vẹn một dự án từ đầu đến cuối và bảo vệ kết quả trước người phản biện.","000000"),

...baiTap({id:"16",ten:"Phản biện một bài phân tích",cap:"Thử thách",duLieu:"Bài của nhóm khác hoặc bài mẫu trong repo",thoiGian:"90 phút",
 boiCanh:"Trong thực tế, kỹ năng đọc và phản biện một bài phân tích của người khác quan trọng không kém kỹ năng tự làm. Bài này bạn đóng vai người phản biện khó tính.",
 yeuCau:[
  "Nhận một bài phân tích hoàn chỉnh (của nhóm khác, hoặc dùng báo cáo mẫu có sẵn trong kho tài liệu).",
  "Chạy lại ít nhất năm con số được trích dẫn trong bài. Lập bảng đối chiếu.",
  "Rà soát bài theo đủ bảy câu hỏi trong danh sách kiểm tra trước khi tin AI.",
  "Tìm mọi câu dùng từ chỉ nhân quả không có cơ sở và đề xuất cách diễn đạt đúng.",
  "Kiểm tra phần hạn chế: bài đã nêu đủ chưa? Thiếu hạn chế nào?",
  "Viết một bản nhận xét phản biện dài 1 đến 2 trang, nêu cả điểm mạnh lẫn điểm cần sửa, mỗi nhận xét kèm bằng chứng.",
 ],
 sanPham:"Bảng đối chiếu số liệu, bảng rà soát bảy câu hỏi, và bản nhận xét phản biện 1–2 trang.",
 goiY:"Phản biện tốt không phải là chê. Hãy nêu rõ điểm mạnh trước, rồi mới nêu vấn đề, và với mỗi vấn đề hãy đề xuất cách sửa cụ thể chứ không chỉ chỉ ra lỗi.",
 diem:[["Chạy lại và đối chiếu đủ năm con số","2"],["Rà soát đủ bảy câu hỏi kiểm tra","2"],
       ["Phát hiện đúng các câu suy diễn nhân quả","1,5"],["Đánh giá đúng phần hạn chế","1,5"],
       ["Nhận xét cân bằng, mỗi ý có bằng chứng","3"]]}),
PB(),

...baiTap({id:"17",ten:"Dự án phân tích hoàn chỉnh",cap:"Thử thách",duLieu:"Tự chọn một bộ dữ liệu mới",thoiGian:"2 tuần (làm nhóm)",
 boiCanh:"Bài tổng kết của toàn khóa. Bạn đi trọn vẹn năm bước của quy trình trên một bộ dữ liệu chưa từng phân tích, và trình bày kết quả trước lớp.",
 yeuCau:[
  "Chọn một bộ dữ liệu mới, không dùng lại hai bộ đã học. Nêu lý do chọn và câu hỏi nghiên cứu.",
  "Thực hiện đủ năm bước: khám phá, tiền xử lý, trực quan hóa, rút tri thức, trình bày.",
  "Trong phần tiền xử lý, phải có nhật ký đầy đủ.",
  "Vẽ tối thiểu bốn biểu đồ tuân thủ một quy ước thiết kế thống nhất.",
  "Rút ra ít nhất ba tri thức, trong đó tối thiểu một điều đi ngược trực giác thông thường.",
  "Chạy đủ bảy câu hỏi trong danh sách kiểm tra và báo cáo kết quả rà soát.",
  "Viết phần hạn chế nêu tối thiểu bốn điểm, kèm hệ quả khi diễn giải.",
  "Nêu rõ đã dùng công cụ AI nào, ở bước nào, kiểm chứng ra sao.",
  "Trình bày 12 phút trước lớp và trả lời phản biện.",
 ],
 sanPham:"Tệp dữ liệu đã xử lý, mã nguồn đầy đủ, báo cáo viết, bộ slide trình bày, và phần trả lời phản biện.",
 goiY:"Hãy chọn bộ dữ liệu có ít nhất 1.000 dòng và 10 biến — nhỏ quá thì không đủ chất liệu để rút tri thức, lớn quá thì không kịp xử lý trong hai tuần.",
 diem:[["Chọn dữ liệu và câu hỏi nghiên cứu rõ ràng","1"],["Tiền xử lý đúng, có nhật ký","2"],
       ["Bốn biểu đồ đồng bộ, đúng nguyên tắc","2"],["Ba tri thức, có điều đi ngược trực giác","2"],
       ["Rà soát đủ bảy câu hỏi kiểm tra","1"],["Phần hạn chế đủ bốn điểm","1"],
       ["Trình bày và trả lời phản biện","1"]]}),
PB(),

...baiTap({id:"18",ten:"Từ dữ liệu đến đề xuất can thiệp",cap:"Thử thách",duLieu:`${SD_C} hoặc ${AS_C}`,thoiGian:"90 phút",
 boiCanh:"Phân tích chỉ có giá trị khi ai đó làm khác đi nhờ nó. Bài này yêu cầu bạn chuyển kết quả thống kê thành một đề xuất mà nhà trường có thể thực hiện được.",
 yeuCau:[
  "Chọn ba phát hiện mạnh nhất từ các bài trước.",
  "Với mỗi phát hiện, đề xuất một biện pháp can thiệp cụ thể, nêu rõ: ai làm, làm gì, làm khi nào, đo kết quả bằng chỉ số nào.",
  "Với mỗi đề xuất, chỉ rõ nó dựa trên con số nào trong phân tích của bạn.",
  "Đánh giá tính khả thi: biện pháp nào rẻ và dễ làm, biện pháp nào tốn kém. Xếp thứ tự ưu tiên.",
  "Nêu rõ giới hạn: vì dữ liệu chỉ cho thấy tương quan, đề xuất của bạn dựa trên giả định nhân quả nào? Giả định đó có hợp lý không?",
  "Thiết kế cách kiểm chứng: nếu triển khai, làm thế nào biết biện pháp có hiệu quả?",
 ],
 sanPham:"Bảng ba đề xuất với đầy đủ thông tin, bảng xếp hạng ưu tiên theo khả thi, và một đoạn về giả định nhân quả cùng cách kiểm chứng.",
 goiY:"Đề xuất tốt phải cụ thể đến mức người đọc hình dung được tuần sau bắt đầu từ đâu. “Nâng cao nhận thức về sức khỏe tâm thần” là khẩu hiệu, không phải đề xuất. “Lồng sàng lọc năm câu hỏi vào tuần sinh hoạt công dân đầu khóa” mới là đề xuất.",
 diem:[["Ba đề xuất cụ thể, đủ bốn thông tin","3"],["Mỗi đề xuất gắn với con số cụ thể","2"],
       ["Xếp ưu tiên theo khả thi có lập luận","2"],["Nêu rõ giả định nhân quả","1,5"],
       ["Thiết kế được cách kiểm chứng","1,5"]]}),
PB(),
];
